version: '2.1'
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest 
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: cms
      MYSQL_ROOT_PASSWORD: 123456
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=123456 --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
 
    
  ginserver:
    depends_on:
      mysql:
        condition: service_healthy
    #   redis:
    #     condition: service_healthy
    container_name: ginserver
    restart: always
    image: zhaoqiandocker/webback:0.1.2
    expose:
      - '8008'
    environment:
      MYSQL_DSN: root:123456@(mysql)/cms?charset=utf8mb4&parseTime=True&loc=Local
      # REDIS_ADDR: redis:6379
      # REDIS_DB: 0
      #REDIS_PW: 
      SESSION_SECRET: setOnProducation
      GIN_MODE: debug
      # LOG_LEVEL: debug
    # healthcheck:
    #   test: "curl localhost:8080/api/v1/ping"
    #   interval: 10s
    #   timeout: 1s
    #   retries: 5
  frontend:
    container_name: nginx
    restart: always
    image: zhaoqiandocker/nginx
    ports:
      - '8080:80'